name: Continuous update

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  continuous-update:
    name: Continuous update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
      pull-request-url: ${{ steps.pr.outputs.pull-request-url }}
      pull-request-operation: ${{ steps.pr.outputs.pull-request-operation }}
      pull-request-head-sha: ${{ steps.pr.outputs.pull-request-head-sha }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Dockerfile
        run: ./update.sh
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update on ${{steps.date.outputs.date}}
          title: Continuous update on ${{steps.date.outputs.date}}
          body: |
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          branch: continuous-update/${{steps.date.outputs.date}}
          branch-suffix: timestamp
          delete-branch: true
          reviewers: silver886

  ci:
    name: CI
    needs: continuous-update
    uses: ./.github/workflows/ci.yaml
    with:
      git_sha: ${{ needs.continuous-update.outputs.pull-request-head-sha }}
