name: Continuous update

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  continuous-update:
    name: Continuous update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Get current date
        id: date
        run: echo "name=date::$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update Dockerfile
        run: ./update.sh
      - name: Create Token
        id: token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.token.outputs.token }}
          commit-message: Update on ${{steps.date.outputs.date}}
          title: Continuous update on ${{steps.date.outputs.date}}
          body: |
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          branch: continuous-update/${{steps.date.outputs.date}}
          branch-suffix: timestamp
          delete-branch: true
          reviewers: silver886
