name: Release ISO

on:
  release:
    types:
      - created
  workflow_call:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare environment
        run: docker system prune --all --force --volumes
      - name: Happy Eyeballs
        run: wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
      - name: Check kernel config
        run: |
          kernDups="$(files/kernel-config.d/.check-dups.sh)"
          if [ -n "$kernDups" ]; then
            echo >&2 "KERNEL CONFIG DUPLICATES!"
            echo >&2 "$kernDups"
            exit 1
          fi
      - name: Build ISO
        run: |
          set -Eeuo pipefail -x
          docker build -t boot2docker .
          docker_container_id=$(docker create boot2docker)
          docker cp $docker_container_id:/tmp/boot2docker.iso boot2docker.iso
          docker cp $docker_container_id:/tmp/stats/state.md state.md
          docker cp $docker_container_id:/tmp/stats/sums.md sums.md
          docker rm $docker_container_id
          cat state.md > release.md
          cat sums.md >> release.md
      - name: '"ls"'
        run: ls -lh boot2docker.iso
      - name: '"docker images"'
        run: docker images
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: boot2docker.iso
          body_path: release.md
